import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute top-0 flex justify-between w-full p-4 text-black">
            <h1 className="font-bold text-xl"><a href="/">Hello World</a></h1>
            <ul className='flex gap-4 text-2xl'>
                <li><Link href="/">Home</Link></li>
                <li><Link href="/About">About</Link></li>
                <li>
                <Link href='/product-1'>Product 1</Link>
            </li>
            <li>
                <Link href='/product-2'>Product 2</Link>
            </li>
            </ul>
        </nav>
        <main className="w-screen h-screen flex flex-col justify-center items-center text-center bg-gray-400 text-9xl font-bold">
            {children}
        </main>  
      </body>
    </html>
  )
}
